
```{r}
library(MASS)
library(lattice)
library(corrplot)
library(lattice)
library(latticeExtra)
library(impute)
library(ISLR)
library(e1071)
library(nnet)
library(class)
```

Готовим данные
```{r}

make_data <- function(data) {
  data <- na.omit(data)
  data$Film <- NULL
  data$Rating <- round(data$Rating)
  data$Rating <- cut(data$Rating, breaks = c(1, 2.4, 4.9, 7.4, 10), labels = c("Excellent", "Average", "Poor", "Terrible"))
  data <- subset(data, data$Budget > 2000)
  data$Film <- NULL
  data$Popularity <- NULL
  return (data)
}



movies.train <- read.csv("../Data/csv2/file_2_train.csv")
movies.train <- make_data(movies.train)
summary(movies.train$Rating)



movies.test <- read.csv("../Data/csv2/file_2_test.csv")
movies.test <- subset(movies.test, movies.test$Rating < 9.5)
movies.test <- make_data(movies.test)
summary(movies.test$Rating)
levels(movies.test$Rating)

```

Посмотрим на графики
```{r}
marginal.plot(movies.train)
marginal.plot(log(movies.train$Budget))
marginal.plot(movies.train, data = movies.train, groups = Rating,auto.key = list(lines = TRUE, title ="Rating",cex.title = 1, columns = 3))
```

Строим модели:

***LDA***
```{r}

build_and_test_lda <- function(formula) {
  model <- lda(formula , data = movies.train)
  print(model)

  print(tune(lda, formula, data = movies.train, predict.func = function(...) predict(...)$class, tunecontrol = tune.control(sampling = "cross",cross = 10)))
  
  my.predicted <- predict(model, movies.test)
  print(table(predicted = my.predicted$class, actual = movies.test$Rating))
  print(mean(my.predicted$class != movies.test$Rating))
}

build_and_test_lda(Rating ~ .)
```

***naive bayes***
```{r}
build_and_test_bayes <- function(formula) {
  model <- naiveBayes(formula , data = movies.train)
  print(model)

  print(tune(naiveBayes, formula, data = movies.train, predict.func = function(...) predict(...), tunecontrol = tune.control(sampling = "cross",cross = 10)))
  
  my.predicted <- predict(model, movies.test)
  print(table(predicted = my.predicted, actual = movies.test$Rating))
  print(mean(my.predicted != movies.test$Rating))
}

build_and_test_bayes(Rating ~ .)

```


***multinomial regression***
```{r}

build_and_test_multinom <- function(formula) {
  model <- multinom(formula , data = movies.train, trace = FALSE, maxit = 3000)
  print(model)

  print(tune(multinom, formula, data = movies.train, trace = FALSE, maxit = 3000, predict.func = function(...) predict(...), tunecontrol = tune.control(sampling = "cross",cross = 10)))
  
  my.predicted <- predict(model, movies.test)
  print(table(predicted = my.predicted, actual = movies.test$Rating))
  print(mean(my.predicted != movies.test$Rating))
  return (model)
}

movies.mn <- build_and_test_multinom(Rating ~ .^2)

```

Поросим stepAIC выбрать параметры
```{r}

movies.AIC <- stepAIC(movies.mn);
movies.mn <- build_and_test_multinom(as.formula(movies.AIC))
build_and_test_lda(as.formula(movies.AIC))
```
Остановимся на модели, построенной методом multinomial regression
